export const SKILLS_DATA = [
 { id: 1, name: "HTML5", icon: null, type: "primary" },
 { id: 2, name: "CSS/SCSS/SASS", icon: null, type: "primary" },
 { id: 3, name: "Tailwind CSS", icon: null, type: "stack" },
 { id: 4, name: "JavaScript", icon: null, type: "primary" },
 { id: 5, name: "TypeScript", icon: null, type: "stack" },
 { id: 6, name: "React.js", icon: null, type: "stack" },
 { id: 7, name: "Next.js", icon: null, type: "stack" },
 { id: 8, name: "Redux Toolkit", icon: null, type: "primary" },
 { id: 9, name: "RTK Query", icon: null, type: "primary" },
 { id: 10, name: "Node.js", icon: null, type: "primary" },
 { id: 28, name: "Express.js", icon: null, type: "primary" },
 { id: 11, name: "Nest.js", icon: null, type: "stack" },
 { id: 12, name: "MongoDB", icon: null, type: "primary" },
 { id: 13, name: "SQL", icon: null, type: "stack" },
 { id: 14, name: "API Integration", icon: null, type: "primary" },
 { id: 15, name: "AI Integration", icon: null, type: "primary" },
 { id: 16, name: "Web Sockets", icon: null, type: "primary" },
 { id: 17, name: "Git", icon: null, type: "primary" },
 { id: 18, name: "Code Testing and Debugging", icon: null, type: "primary" },
 { id: 19, name: "Code Analysis and Refactoring", icon: null, type: "primary" },
 { id: 20, name: "Problem Solving", icon: null, type: "secondary" },
 { id: 21, name: "Project Management", icon: null, type: "secondary" },
 { id: 22, name: "Research Skills", icon: null, type: "secondary" },
 { id: 23, name: "Communication", icon: null, type: "secondary" },
 { id: 24, name: "Visual Studio Code", icon: null, type: "secondary" },
 { id: 25, name: "Microsoft Office", icon: null, type: "secondary" },
 { id: 26, name: "Inkscape", icon: null, type: "secondary" },
 { id: 27, name: "Figma", icon: null, type: "secondary" },
] as const;
