export const TECHNOLOGIES_DATA = [
 { id: 1, name: "Socket.io", icon: null },
 { id: 2, name: "React Hook Form", icon: null },
 { id: 3, name: "Zod", icon: null },
 { id: 4, name: "Formik", icon: null },
 { id: 5, name: "Yup", icon: null },
 { id: 6, name: "Docker", icon: null },
 { id: 7, name: "Prisma", icon: null },
 { id: 8, name: "Drizzle", icon: null },
 { id: 9, name: "i18next", icon: null },
 { id: 10, name: "jQuery", icon: null },
 { id: 11, name: "GraphQL", icon: null },
 { id: 12, name: "Apollo Client/Server", icon: null },
 { id: 13, name: "JWT", icon: null },
 { id: 14, name: "Tanstack Query", icon: null },
 { id: 15, name: "Jest", icon: null },
 { id: 16, name: "React Testing Library", icon: null },
 { id: 17, name: "Directus CMS", icon: null },
 { id: 18, name: "Strapi", icon: null },
 { id: 19, name: "Firebase", icon: null },
 { id: 20, name: "Supabase", icon: null },
 { id: 21, name: "Material UI", icon: null },
 { id: 22, name: "MDX", icon: null },
 { id: 23, name: "Framer Motion", icon: null },
 { id: 24, name: "GSAP", icon: null },
 { id: 25, name: "Vite", icon: null },
 { id: 26, name: "Webpack", icon: null },
 { id: 27, name: "Gulp", icon: null },
 { id: 28, name: "Agile Methodology", icon: null },
] as const;
